version: "3"
services:
  # mongodb replicaset primary
  mongod1:
    container_name: mongod1
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - ${MONGODB_PORT}:27017
    volumes:
      - $PWD/volumes/mongodbdata1:/data/db
      - $PWD/replica.key:/data/replica.key
    depends_on:
      - mongod2
      - mongod3
    restart: always
    command: "mongod --bind_ip_all --replSet dbrs --keyFile /data/replica.key"

  # mongodb replicaset secondary
  mongod2:
    container_name: mongod2
    image: mongo:6.0
    expose:
      - 27017
    volumes:
      - $PWD/volumes/mongodbdata2:/data/db
      - $PWD/replica.key:/data/replica.key
    restart: always
    command: "mongod --bind_ip_all --replSet dbrs --keyFile /data/replica.key"

  # mongodb replicaset arbiter
  mongod3:
    container_name: mongod3
    image: mongo:6.0
    expose:
      - 27017
    volumes:
      - $PWD/volumes/mongodbdata3:/data/db
      - $PWD/replica.key:/data/replica.key
    restart: always
    command: "mongod --bind_ip_all --replSet dbrs --keyFile /data/replica.key"

  mongo-setup:
    image: mongo:6.0
    container_name: mongo-setup
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    depends_on:
      - mongod1
      - mongod2
      - mongod3
    volumes:
      - $PWD/mongodb_rs_init.sh:/scripts/mongodb_rs_init.sh
    restart: on-failure
    entrypoint: ["/bin/bash", "/scripts/mongodb_rs_init.sh"]

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - ${MONGOEXP_PORT}:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      ME_CONFIG_MONGODB_URL: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongod1:27017/?replicaSet=dbrs"
    depends_on:
      - mongod1
